# Pain au Choc ultimate de Ouf profile: aggressive
enabled=true
qualityLevel=6
dynamicResolutionEnabled=true
dynamicResolutionMinScale=0.64
adaptiveSimulationDistanceEnabled=true
cpuInvolvementLevel=3
frameTimeStabilizerEnabled=true
gpuBottleneckDetectorEnabled=true
advancedSharpeningEnabled=true
advancedSharpeningStrength=0.48
