# Pain au Choc ultimate de Ouf profile: stable
enabled=true
qualityLevel=7
dynamicResolutionEnabled=true
dynamicResolutionMinScale=0.70
adaptiveSimulationDistanceEnabled=true
cpuInvolvementLevel=3
frameTimeStabilizerEnabled=true
gpuBottleneckDetectorEnabled=true
advancedSharpeningEnabled=true
advancedSharpeningStrength=0.40
