# Pain au Choc ultimate de Ouf profile: baseline_off
enabled=false
qualityLevel=10
dynamicResolutionEnabled=true
dynamicResolutionMinScale=0.70
adaptiveSimulationDistanceEnabled=true
cpuInvolvementLevel=3
frameTimeStabilizerEnabled=true
gpuBottleneckDetectorEnabled=true
advancedSharpeningEnabled=true
advancedSharpeningStrength=0.40
